config/routes.rb
Codereview::Application.routes.draw do
  devise_for :users

  resources :codes
  resources :comments
  resources :weeks
  
  root :to => "Weeks#index"

end

app/models/code.rb
class Code < ActiveRecord::Base
  attr_accessible :title, :user_id, :post, :week_id
  
  belongs_to :user
  belongs_to :week
  has_many :comments
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :user_id, :code_id, :parent_comment_id
  
  belongs_to :user
  belongs_to :code
  belongs_to :parent_comment, class_name: "Comment"
  has_many :child_comments, class_name: "Comment", foreign_key: :parent_comment_id
  
  
  def self.comments_by_parent(code_id)
    comments = Hash.new{|hash, key| hash[key] = []}
    Comment.where("code_id = ?", code_id).each do |comment|
      comments[comment.parent_comment_id] << comment
    end
    
    comments
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :codes
  has_many :comments
end

app/models/week.rb
class Week < ActiveRecord::Base
  attr_accessible :code_id, :title, :description
  
  has_many :codes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
   before_filter :authenticate_user!, except: [:index, :show]
  
  def index
    @codes = Code.all.reverse
  end
  
  def new
    @code = Code.new
  end
  
  def create
    @code = Code.create(params[:code])
    @code.user_id = current_user.id
    if @code.save
      redirect_to @code
    else
      flash[:error] = "Failed to save"
      render :new
    end
  end
  
  def show
    @code = Code.find(params[:id])
    @comments = Comment.comments_by_parent(params[:id])
  end
  
  def edit
    @code = Code.find(params[:id])
  end
  
  def update
    @code = Code.find(params[:id])
    if @code.update_attributes(params[:code])
      redirect_to @code
    else
      flash[:error] = "Failed to edit"
      render :edit
    end
  end
  
  def destroy
    @code = Code.find(params[:id])
    if @code.destroy
      render :index
    else
      flash[:error] = "Failed to delete"
      render :edit
    end
    
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
  end
  
  def create
    @comment = Comment.new(params[:comment])
    @comment.user_id = current_user.id
    
    if @comment.save
      redirect_to Code.find(@comment.code_id)
    else
      flash[:error] = "Comment not saved"
      render :back
    end
  end
  
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  
  def index
    @weeks = Week.find(:all, :include => :codes)
  end
  
  def new
    @week = Week.new
  end
  
  def create
    @week = Week.new(params[:week])
    if @week.save
      render :index
    else
      flash[:error] = "Failed to save week"
      render :new
    end
  end
  
  def show
    @week = Week.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/codes/_code.html.erb
<li><a href="<%= code_url(code) %>"><%= code.title %></a> by <%= code.user.email %>
	<br>
	<br>
	<div class="resizable">
		<%= code.post.html_safe %>
	</div>
</li>

app/views/codes/index.html.erb
<h1>Code Index</h1>

<%= link_to "Add Code", new_code_url %>

<ul class="code-list">
	<%= render @codes %>
	<br>
</ul>

<script>
$(document).ready(function() {
	$('.resizable').resizable()
});
</script>

app/views/codes/new.html.erb
<h1>Add New Code</h1>
<h3>Use <a href="http://pastebin.com/">Pastebin</a> to add your code. Use the iframe embedding option.</h3>

<form action="<%= codes_url %>" method="post" >
	
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	
	<label for="code_title">Code title</label>
	  <input type="text" id="code_title" name="code[title]"
	  value="">
		
		<br>
		
		<label for="code_content">Code Content</label>
		<textarea rows='6' cols='100' name="code[post]">
			Put pastebin embed (iframe) code here with comments.
		</textarea>
		
		<br>
		
		<label for"code_week">Week</label>
		<input type="number" name="code[week_id]" id="code_week">
		
		<br>
		
		<input type="submit" value="Submit new code">
	
</form>

app/views/codes/show.html.erb
<%= render @code %>

<br>
Add New Comment
<form action="<%= comments_url %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<input type="hidden" name="comment[code_id]" value="<%= @code.id %>">
	<textarea rows='6' cols='100' name="comment[content]"></textarea>
	
	<input type="submit" name="Add new comment">
</form>


<ul>
	<% @comments[nil].each do |parent| %>
			<%= render partial: "comments/comment", locals: {comment: parent, comments: @comments} %>
	<% end %>
</ul>

<%= link_to "Back to index", root_path %>

<script>

$(document).ready(function() {
	$('.resizable').resizable()
});

</script>

app/views/comments/_comment.html.erb
<%= comment.user.email %> says at <%= comment.updated_at %>
<br>
<%= comment.content.html_safe %>
<br>
<br>

<ul>
	<% comments[comment.id].each do |child| %>
		<li>
			<%= render partial: "comments/comment", locals: { comment: child, comments: comments } %>
		</li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codereview</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="alert"><%= alert %></p>
	<p class="notice"><%= notice %></p>

<%= yield %>

</body>
</html>

app/views/weeks/_week.html.erb
<li>
	<h3><%= link_to week.title, week  %></h3>
	<h4><%= week.description %></h4>
	<%= render week.codes %>
</li>

app/views/weeks/index.html.erb
<h1>Learn Python the Hard Way - Code Review</h1>

<ul>
	<%= render @weeks %>
</ul>

<%= link_to "Create new week", new_week_url %>

<script>

$(document).ready(function() {
	$('.resizable').resizable()
});

</script>

app/views/weeks/new.html.erb
<h1>New Week</h1>

<form action="<%= weeks_url %>" method="POST">
	
	<input type="hidden" name="form_authenticity" value="<%= form_authenticity_token %>">
	
	<label for="week_title">Week Title</label>
	<input type="text" name="week[title]" id="week_title">
	
	<label for="week_description">Description</label>
	<input type="text" name="week[description]" id="week_description">
	
	<input type="submit" value="Add New Week">
</form>

app/views/weeks/show.html.erb
<%= render @week %>

<%= link_to "New Code Post", new_code_url %>